#!/usr/bin/env bash
# Script to configure a new Ubuntu machine
# with Nginx to serve a "Hello World" page
# and set up a redirection and custom header

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service and allowing on firewall
sudo service nginx start
# Create index.html with "Hello World!"
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Update Nginx configuration to add redirection
sudo sed -i '/^}$/i \ \n\trewrite ^/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply changes
service nginx restart
