#!/usr/bin/env bash
# Installs Nginx, creates a simple Hello World page,
# and configures a custom 404 page to show a message

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
    sudo apt-get install -y nginx

echo -e "\nSetting up some minor configurations.\n"

# Starting the Nginx service and allowing Nginx on the firewall
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Giving the user ownership of the website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backing up the default index page
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating a new index page
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
NGINX_CONF="/etc/nginx/sites-available/default"

# Backup the default configuration file
cp $NGINX_CONF "${NGINX_CONF}.bak"

# Update the configuration file to define the custom error page
sed -i '/error_page 404/i\    error_page 404 /custom_404.html;' $NGINX_CONF
sed -i '/location \//a\        error_page 404 /custom_404.html;' $NGINX_CONF


# Restarting Nginx to apply changes
sudo service nginx restart
echo -e "\nCompleted.\n"
