#!/usr/bin/env bash
# a script to fix port 80 on nginx and close it at the end
ln -sf /etc/nginx/sites_available/default /etc/nginx/sites_enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
